### ISSUE TITLE
Ability to provide env values 

### ISSUE THREAD

**Issue by pubudu538** [wso2-incubator/wso2am-k8s-operator#76]
Users should be able to add env values.

```
spec:
  pattern: Pattern-1
  profiles:
    - name: api-manager-1
      deployment:
        envs:
        - "key":"value"
```
