### ISSUE TITLE
Creating Pattern-X with persistentVolumeClaims for synapseConfigs and executionPlans

### ISSUE THREAD

**Issue by harmen1994** [wso2-incubator/wso2am-k8s-operator#82]
Hello fellow WSO2 developers,

Currently trying to get two persistentVolumeClaims for the WSO2 API Manager by following the [documentation](https://github.com/wso2/k8s-wso2am-operator/blob/master/docs/HowToGuide/configure-own-custom-pattern.md).
We use Pattern-X since we want to distribute 2 WSO2 API Managers over 2 Kubernetes nodes and we require a custom Galera database.
When applying this config no PVC's are created and mounted. I searched in the code and saw that these configs: synapseConfigs and executionPlans are not yet included in code. Is this something that is on WSO2's roadmap? If not, I can check if I can add this to the operator, however I don't have much GO experience yet.

Thanks in advance for taking a look at this question!

Kind regards,
Harmen

```
apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: custom-pattern
spec:
  pattern: Pattern-X
  service:
    type: NodePort
  profiles:
    - name: api-manager
      type: api-manager
      service:
        name: wso2apim
      deployment:
        replicas: 2
        configMaps:
          deploymentConfigMap: apim-conf
        resources:
          requests:
            memory: 10Mi
            cpu: 20m
          limits:
            memory: 2Gi
            cpu: 2000m
        persistentVolumeClaim:
          synapseConfigs: wso2-am-shared-synapse-configs-volume-claim
          executionPlans: wso2-am-shared-executionplans-volume-claim
```

**Comment by pubudu538** [comment]
Are you using Operator v1.1.0? https://github.com/wso2/k8s-wso2am-operator/tree/v1.1.0/scenarios/scenario-1

In v1.1.0 we have that support - https://github.com/wso2/k8s-wso2am-operator/blob/v1.1.0/pkg/controller/patternX/volumes.go#L29

But in the master, we have improved this where we don't have NFS for data sharing specially Synapse artifacts - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster/#inbuilt-artifact-synchronization

**Comment by harmen1994** [comment]
Thanks for your fast response @pubudu538.

Currently I'm using the master branch since that would easily sync with ArgoCD. It is great to hear that WSO2 came up with a sync function, I'd prefer to get that working and that means less moving parts. If this doesn't work I'll reopen this one.

Example code of ArgoCD to install the operator automatically:
```
# This file is for local developmment to add the operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ont-wso2-apimanager-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ont-wso2am
    server: https://kubernetes.default.svc
  project: default
  source:
    path: artifacts
    repoURL: https://github.com/wso2/k8s-wso2am-operator.git
    targetRevision: HEAD
    directory:
        recurse: true
        exclude: artifacts/api-manager-artifacts/pattern-[!1]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
